# Generated by Django 5.0.7 on 2024-08-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userportal", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link_path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="link_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
